FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl wget vim nano git && \
    apt-get clean

ENV USER_HOME=/home/dockeruser

RUN useradd -m dockeruser

USER dockeruser

CMD ["bash"]
