FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root123
ENV MYSQL_DATABASE=mi_basededatos
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=usuario_password

COPY init.sql /docker-entrypoint-initdb.d/

VOLUME /var/lib/mysql

EXPOSE 3306